print("公司入职手续")
name = input("姓名:")
age = input("年龄:")
sex = input("性别:")
high = float(input("身高:"))
weight = float(input("体重:"))
ID_number = int(input("身份证号:"))
xueli = input("学历:")
birthday = input("出生年月:")
jtzz = input("家庭住址:")
phone = int(input("电话号码:"))
zhiwei = input("职位:")
money = input("薪水:")
print('*'*10)
print("姓名%s\n年龄%s\n性别%s\n身高%s\n体重%s\n身份证号%s\n学历%s\n出生年月%s\n家庭住址%s\n电话号码%s\n职位%s\n薪水%s\n"%(name,age,sex,high,weight,ID_number,xueli,birthday,jtzz,phone,zhiwei,money))
print('*'*10)
