print("欢迎使用美时美刻便利店")
spmc = input("商品名称:")
sl = input("数量:")
dj = input("单价:")
zj = input("总价:")
sk = input("收款:")
zh = input("找回:")
sh = input("实收")
print("*"*10)
print("商品名称%s\n数量%s\n单价%s\n总价%s\n收款%s\n找回%s\n实收%s\n"%(spmc,sl,dj,zj,sk,zh,sh))
print("*"*10)
