print("房屋销售")
fwdx = input("房屋大小:")
dwmj = input("房屋面积:")
szcs = input("所处城市:")
xxwz = input("所在详细位置:")
money = input("价格:")
name = input("购房顾问:")
print("*"*10)
print("房屋大小%s\n房屋面积%s\n所处城市%s\n所在详细位置%s\n价格%s\n购房顾问%s\n"%(fwdx,dwmj,szcs,xxwz,money,name))
print("*"*10)
